# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pkt_to_xml

on:
  push:
    tags:
      - 'p2x/**'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Checkout pka2xml
        uses: actions/checkout@v5
        with:
          repository: THE-SIMPLE-MARK/pka2xml
          path: pka2xml

      - name: Setup pka2xml
        working-directory: ./pka2xml
        run: ./build-linux.sh

      - name: Convert pkt to xml
        run: pka2xml/pka2xml -d deeptech.pkt deeptech.xml

      - name: Commit converted file to git
        run: |
          git config --local user.name  ${{ github.actor }}        
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add deeptech.xml
          git commit -m "chore: generate new xml"

      - name: Convert tag to branch
        id: get_branch
        run: |
          # Get the branch name(s) containing the commit pointed to by the tag
          # The --format="%(refname:lstrip=3)" extracts the branch name without "refs/remotes/origin/"
          branch_name=$(git branch -r --contains ${{ github.ref }} --format="%(refname:lstrip=3)")
          
          # If multiple branches contain the commit, you might need to handle this.
          # For simplicity, this example assumes a single primary branch.
          # You can add logic to select a specific branch if needed.
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT
          echo "Branch is $branch_name."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.get_branch.outputs.branch_name }}